name: woost_games
description: The amazing Woost Games!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Neue Montreal
      fonts:
        - asset: assets/fonts/NeueMontreal/NeueMontreal-Regular.otf
        - asset: assets/fonts/NeueMontreal/NeueMontreal-Bold.otf
          weight: 700
  uses-material-design: true